name: portfolio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # IOS Icons
  cupertino_icons: ^1.0.2

  # For responsive design
  responsive_builder: ^0.4.1

  # To display icons
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - lib/assets/icons/
      - lib/assets/images/

  fonts:
      - family: ChalkboardSE
        fonts:
          - asset: lib/assets/fonts/ChalkboardSE.ttf